### ISSUE TITLE
Debian Stretch amd64

### ISSUE THREAD

**Issue by nt74** [lelegard/dektec-dkms#1]
This script doesn't work on Debian Stretch amd64 platform. Is it possible to add support for it?

**Comment by lelegard** [comment]
Hi,

Could you be more specific please? What does "does not work" mean here? 

The script works on recent versions of Ubuntu. I do not have any Debian system to test. How do you characterise a Debian version ? Do you have a `/etc/lsb-release` file as in Ubuntu ? Do you have a `/etc/debian_version` file as I can see in my Raspbian (Raspberry Pi) and what is its content ?

**Comment by nt74** [comment]
Hi,

What does not work? -The script cannot find the name of the Linux distro.
Here is the script with the /bin/bash -x flag: 
[debian9.5_issue.txt](https://github.com/tsduck/dektec-dkms/files/2516565/debian9.5_issue.txt)

```
$ ./build-dektec-dkms -v
build-dektec-dkms: downloading https://www.dektec.com/products/SDK/DTAPI/Downloads/LinuxSDK_v2018.07.0.tar.gz
build-dektec-dkms: actual file name: LinuxSDK_v2018.07.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.0M  100 26.0M    0     0  1970k      0  0:00:13  0:00:13 --:--:-- 1342k
build-dektec-dkms: package version is 2018.07.0
build-dektec-dkms: expanding /home/nettan/dektec-dkms/LinuxSDK_v2018.07.0.tar.gz
build-dektec-dkms: building DKMS structure in /home/nettan/dektec-dkms/tmp/dektec-dkms-2018.07.0/dektec-2018.07.0
build-dektec-dkms: creating /home/nettan/dektec-dkms/packages/dektec-dkms-2018.07.0.tgz
build-dektec-dkms: Linux distro: , full version: 
build-dektec-dkms: unsupported Linux distro
```
Do you have a /etc/lsb-release file as in Ubuntu ? -No.
Do you have a /etc/debian_version ? -Yes, "9.5".

**Comment by lelegard** [comment]
I have pushed a fix which builds the .deb package on a Raspbian and should hopefully work on Debian.

Please close this issue if this fixes your problem.

**Comment by nt74** [comment]
Many thanks @lelegard the debian package is created correctly however I get a new issue.

I have successfully built the DTA driver (which I need) by entering the folder
`dektec-dkms/LinuxSDK/Drivers/Dta/Source/Linux`
and using `make` and `sudo make install`.

However I cannot install the debian package via the dkms method.

```
Selecting previously unselected package dektec-dkms.
(Reading database ... 156179 files and directories currently installed.)
Preparing to unpack dektec-dkms_2018.07.0_all.deb ...
Unpacking dektec-dkms (2018.07.0) ...
D000400:   checking group ...
D000400:     checking possibility  -> dkms
D000400:       checking non-provided pkg dkms:all
D000400:       is installed, ok and found
D000400:     found 3
D000400:   found 3 matched 0 possfixbytrig -
D000400:   checking group ...
D000400:     checking possibility  -> linux-headers
D000400:       not installed
D000400:         returning 0
D000400:     found 0
D000400:   found 0 matched 0 possfixbytrig -
dpkg: dependency problems prevent configuration of dektec-dkms:
 dektec-dkms depends on linux-headers; however:
  Package linux-headers is not installed.

dpkg: error processing package dektec-dkms (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dektec-dkms
```
I have installed all necessary packages for the make file:
```
sudo apt install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-4.9.0-8-amd64 is already the newest version (4.9.110-3+deb9u6).
linux-headers-4.9.0-8-amd64 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done
linux-headers-4.9.0-8-amd64/stable,now 4.9.110-3+deb9u6 amd64 [installed,automatic]
  Header files for Linux 4.9.0-8-amd64
```
```
sudo apt install dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  linux-headers-amd64
Suggested packages:
  python3-apport menu
The following NEW packages will be installed:
  dkms linux-headers-amd64
```

**Comment by lelegard** [comment]
The package `dkms` is, by definition, a dependency of all DKMS driver packages. And Linux headers is a natural dependency of DKMS because the purpose of DKMS is automatic recompilation of drivers on kernel upgrades and recompiling a driver requires Linux headers. All of these are normal.

So, now, you have rebuilt `dektec-dkms` and installed `dkms` and  `linux-headers-amd64`. You should be able to install `dektec-dkms`. Does this work? Are the Dektec drivers automatically recompiled on kernel upgrades? You reopened the issue, so you must have some problem. But your last message is not clear about what it is precisely.

**Comment by nt74** [comment]
I can build the deb package but I cannot install it, so it doesn't work.
I receive the errors: 
```
dpkg: dependency problems prevent configuration of dektec-dkms:
 dektec-dkms depends on linux-headers; however:
  Package linux-headers is not installed.
```
Even though it is installed. I can however build it from the linux sources.

**Comment by lelegard** [comment]
It seems that Ubuntu and Debian use distinct package names for kernel headers. I just pushed a fix. Could you please rebuild the dektec-dkms package and retry the installation.

**Comment by nt74** [comment]
It works perfect now. Many thanks for the help @lelegard.

```
$ apt list --installed | grep dektec
dektec-dkms/now 2018.07.0 all [installerat,lokalt]
```
