### ISSUE TITLE
New driver DtPcieNw added starting from SDK 2023.08.0

### ISSUE THREAD

**Issue by nt74** [lelegard/dektec-dkms#5]
Hello,
new driver added called `DtPcieNw`, a network driver for DTA-2110 DekTec cards.
You can add this driver to the `dkms.conf` and `Makefile`.

**Comment by lelegard** [comment]
Hi @nt74 

Thanks for reporting this. The packages were fixed. Version 2023.08.0.1 was just released in this project. The packages are still named 2023.08.0 because this is the Dektec version name.
